SELECT s.NAME, bs.NAME, bs.DATE
FROM SHIPS s JOIN (SELECT b.NAME, b.DATE, o.SHIP
					FROM BATTLES b JOIN OUTCOMES o
						ON b.NAME = o.BATTLE
					WHERE o.RESULT = 'sunk') bs
	ON s.NAME = bs.SHIP
ORDER BY bs.NAME