SELECT p2.NAME, c.DISPLACEMENT, c.NUMGUNS, p2.RESULT
FROM CLASSES c JOIN ( SELECT s.NAME, p1.RESULT, s.CLASS
						FROM SHIPS s JOIN ( SELECT o.RESULT,o.SHIP
											FROM OUTCOMES o JOIN BATTLES b
												ON o.BATTLE = b.NAME
											WHERE b.NAME = 'North Atlantic') p1
						ON s.NAME = p1.SHIP) p2
	ON c.CLASS = p2.CLASS