SELECT DISTINCT me.NAME
FROM MOVIEEXEC me JOIN MOVIE m
	ON me.CERT# = m.PRODUCERC#
WHERE m.TITLE IN ( 
SELECT m.TITLE
FROM MOVIE m JOIN STARSIN ss
	ON m.TITLE = ss.MOVIETITLE
WHERE ss.STARNAME = 'Harrison Ford')