SELECT c.CLASS, COUNT(*) as No_Sunk
FROM CLASSES c JOIN (SELECT s.CLASS
					FROM SHIPS s JOIN OUTCOMES o
						ON s.NAME = o.SHIP
					WHERE o.RESULT = 'sunk') s
	ON c.CLASS = s.CLASS
GROUP BY c.CLASS
HAVING c.CLASS IN
       (SELECT CLASSES.CLASS
        FROM CLASSES JOIN SHIPS
                          ON CLASSES.CLASS = SHIPS.CLASS
        GROUP BY CLASSES.CLASS
        HAVING COUNT(SHIPS.NAME) > 2)